# GENERAL TIP: INDENTATION IS IMPORTANT 
name: Generate Podcast Feed  # you can name workflows 
on: [push] # specifies when the workflow should run 
jobs:  # a list of  jobs that should happen in a workflow 
  build: #this is ONE JOB  
    runs-on: ubuntu-latest #it runs on UBUNTU OS (DOCKER FLASHBACKS XD) 
    steps: #you need to specify steps in a job 
      - name: Checkout Repo # you can optionally name steps,
        uses: actions/checkout@v3 
        # syntax for running a workflow from the marketplace, 
        # The action above is a Github created workflow to checkout a repo, 
        # @vX allows you to specify the version of the worflow you want to use 
      - name: Set Up Python
        uses: actions/setup-python@v4 
        with:
          python-version: "3.10"
        # with allows you to specify arguments for the worflow you important 
      - name: Install Dependecies 
        run: | 
          python -m pip install --upgrade pip
          pip install pyyaml 
        # the |, allows you to have a multiline command 
      - name: Run Feed Generator 
        run: python feed.py 
        # run allows you to run command in the ubuntu terminal ( remember that you spunu up an ubuntu OS sys)  
      - name: Push Repo 
      run: |
        git config  username github-actions 
        git config user.email github-actions@github.com
        # git confid is necessary or else ACTIONS WILL NOT RUN 
        git add . 
        git commit -m "modified feed" 
        git push 
        
        
        
